apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    appOrm: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    name: postgres
